### ISSUE TITLE
Added Map packs in FFXI/ROM No Effect!

### ISSUE THREAD

**Issue by Professor4201** [Drauku/FFXI-Vision#1]
Good afternoon, I followed your install guide by was unable to get them to display with additional mark ups on the maps, my next question is do I also need to put in the other 2 files in the FFXI Folder? Git attributes and Git ignore?

**Comment by Drauku** [comment]
As I'm sure you can tell by the lack of response, I have not been maintaining this repository for quite some time.

Firstly, you do not need the `.gitattributes` or `.gitignore` files for the map replacements to work. The only thing needed is to replace the relevant `.dat` files in your FFXI /ROM/ folder with the `.dat` files in this repository.

Since this repository was released, I believe there is a new Windower and Ashita addon called `XIPivot` that allows you to more easily, and temporarily if desired, replace any FFXI `.dat` file with a modified version. Please search for the `XIPivot` name and there will be a guide on how to set it up with custom `.dat` files.
